#!/bin/bash

BIN_NAME=${1}
WORK_MODE=${2}
WRITEBACK_MODE=${3}
TARGET_DELTA=${4}
CHECK_PREIOD=${5}

FF_INST=100 #in millions
SIM_INST=20 #in millions

ADPAT_WAY_CFG=(0 8 1) # l1, l2, l3
RECONFIG_THRESHOLD_CFG=(1 1 1) # l1, l2, l3
RATIO_CFG=(4 8 1) # l1, l2, l3

WORKLOAD_PATH=./dpc3_traces

SIM_CMD=${BIN_NAME}" "${FF_INST}" "${SIM_INST}
MOSAIC_CACHE_CMD=${WORK_MODE}" "${WRITEBACK_MODE}" "${TARGET_DELTA}" "${CHECK_PREIOD}
MOSAIC_CACHE_L1_OPT=${ADPAT_WAY_CFG[0]}" "${RECONFIG_THRESHOLD_CFG[0]}" "${RATIO_CFG[0]}
MOSAIC_CACHE_L2_OPT=${ADPAT_WAY_CFG[1]}" "${RECONFIG_THRESHOLD_CFG[1]}" "${RATIO_CFG[1]}
MOSAIC_CACHE_L3_OPT=${ADPAT_WAY_CFG[2]}" "${RECONFIG_THRESHOLD_CFG[2]}" "${RATIO_CFG[2]}


for file in $WORKLOAD_PATH/*.champsimtrace.xz
do
	time ./run_champsim_mosaic.sh ${SIM_CMD} ${file##*/} ${MOSAIC_CACHE_CMD} ${MOSAIC_CACHE_L1_OPT} ${MOSAIC_CACHE_L2_OPT} ${MOSAIC_CACHE_L3_OPT}
done


